"""empty message

Revision ID: 18e746c410e0
Revises: 3c059ac851f4
Create Date: 2017-02-06 03:33:29.009000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e746c410e0'
down_revision = '3c059ac851f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.DateTime(), nullable=True))
    op.add_column('service', sa.Column('status', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'status')
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
