"""empty message

Revision ID: 1d43a0f5b353
Revises: 975a59afdd9f
Create Date: 2017-02-09 12:41:07.649468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d43a0f5b353'
down_revision = '975a59afdd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
