"""empty message

Revision ID: 291060f21c30
Revises: 91742b1bc767
Create Date: 2017-02-06 03:28:40

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291060f21c30'
down_revision = '91742b1bc767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('add', sa.DateTime(), nullable=True))
    op.add_column('repository', sa.Column('create', sa.DateTime(), nullable=True))
    op.add_column('repository', sa.Column('push', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'push')
    op.drop_column('repository', 'create')
    op.drop_column('repository', 'add')
    # ### end Alembic commands ###
