"""empty message

Revision ID: 3c059ac851f4
Revises: 291060f21c30
Create Date: 2017-02-06 03:33:11.862000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c059ac851f4'
down_revision = '291060f21c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status')
    op.drop_column('service', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', postgresql.ENUM(u'off', u'on', name='status_types'), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('status', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
