"""empty message

Revision ID: 429bb2bba731
Revises: ade926462c03
Create Date: 2017-02-05 12:56:39.822000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429bb2bba731'
down_revision = 'ade926462c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
