"""empty message

Revision ID: 4a7d74b38564
Revises: 8f8ee6ed0ee3
Create Date: 2017-02-16 16:09:46.859183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7d74b38564'
down_revision = '8f8ee6ed0ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'token')
    # ### end Alembic commands ###
