"""empty message

Revision ID: 71a8d0f0299e
Revises: d67935b4994e
Create Date: 2017-02-06 00:27:48.523000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a8d0f0299e'
down_revision = 'd67935b4994e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watcher', sa.Column('key', sa.String(length=100)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watcher', 'key')
    # ### end Alembic commands ###
