"""empty message

Revision ID: 74a761540b13
Revises: 71a8d0f0299e
Create Date: 2017-02-06 00:46:33.399000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a761540b13'
down_revision = '71a8d0f0299e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watcher', sa.Column('indexer', sa.String(length=90), nullable=True))
    op.drop_column('watcher', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watcher', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('watcher', 'indexer')
    # ### end Alembic commands ###
