"""empty message

Revision ID: 91742b1bc767
Revises: 41f159dba72f
Create Date: 2017-02-06 03:28:20.714000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91742b1bc767'
down_revision = '41f159dba72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'push')
    op.drop_column('repository', 'create')
    op.drop_column('repository', 'add')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('add', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('repository', sa.Column('create', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('repository', sa.Column('push', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
