"""empty message

Revision ID: ade926462c03
Revises: 9dc0fd07f17a
Create Date: 2017-02-05 12:45:58.577000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade926462c03'
down_revision = '9dc0fd07f17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('repository', sa.Column('text', sa.Text(convert_unicode=True), nullable=True))
    op.add_column('repository', sa.Column('text_raw', sa.Text(convert_unicode=True), nullable=True))
    op.add_column('service', sa.Column('api', sa.String(length=100), nullable=False))
    op.add_column('service', sa.Column('params', sa.JSON(), nullable=True))
    op.drop_column('service', 'command')
    op.add_column('user', sa.Column('password_hash', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'nickname')
    op.add_column('watcher', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watcher', 'params')
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.drop_column('user', 'password_hash')
    op.add_column('service', sa.Column('command', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('service', 'params')
    op.drop_column('service', 'api')
    op.drop_column('repository', 'text_raw')
    op.drop_column('repository', 'text')
    op.drop_column('application', 'params')
    # ### end Alembic commands ###
