"""empty message

Revision ID: b25208b4ce0f
Revises: 4a7d74b38564
Create Date: 2017-02-20 11:00:10.189452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25208b4ce0f'
down_revision = '4a7d74b38564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'enabled')
    # ### end Alembic commands ###
